baseURL: "/"
languageCode: "en-us"
title: "Kirill Sysoev — Resume"

params:
  defaultTheme: light
  disableThemeToggle: true
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  mainSections: []

